import time
import logging
import pandas as pd
import ta
from datetime import datetime, timedelta

# ==========================================
# CONFIGURATION & PARAMETERS
# ==========================================
SYMBOL = "CRUDEOILM"
TIMEFRAME = "1min"  # 1-minute timeframe for hyper-scalping

# Risk Management
ALLOCATED_CAPITAL = 50000.0
LOT_SIZE = 10
TICK_SIZE = 1.0

# Point-Based Scalping Targets
TARGET_POINTS = 15.0
SL_POINTS = 8.0
TRAIL_POINTS = 5.0

# Trend & Momentum Filters
EMA_PERIOD = 21
ADX_PERIOD = 14
ADX_THRESHOLD = 20
RSI_PERIOD = 14

# Mode Setup
PAPER_TRADING = False  # Set to False ONLY when ready to risk real capital

# Logging Setup
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# ==========================================
# BROKER INTERFACE (Zerodha KiteConnect Integration)
# ==========================================
try:
    from kiteconnect import KiteConnect
except ImportError:
    logger.error("kiteconnect library not found. Run: pip install kiteconnect")

class BrokerAPI:
    """Live integration with Zerodha KiteConnect API."""
    def __init__(self):
        import os
        # ---------------------------------------------------------
        # TODO: Replace with your actual Zerodha API Key
        # Note: The Access Token is loaded automatically from access_token.txt
        # (Generated by running zerodha_login.py)
        # ---------------------------------------------------------
        self.api_key = "YOUR_ZERODHA_API_KEY"
        self.instruments_cache = None

        self.connect()

    def connect(self):
        """Attempts to establish connection with Zerodha API."""
        import os

        if not os.path.exists("access_token.txt"):
            logger.error("access_token.txt not found! Please run `python zerodha_login.py` first to authenticate for the day.")
            self.connected = False
            return

        with open("access_token.txt", "r") as f:
            access_token = f.read().strip()

        try:
            self.kite = KiteConnect(api_key=self.api_key)
            self.kite.set_access_token(access_token)

            # Simple ping to profile to verify token is valid
            self.kite.profile()

            self.connected = True
            logger.info(f"Zerodha Broker Connected Successfully. Paper Trading Mode: {PAPER_TRADING}")
        except Exception as e:
            self.connected = False
            logger.error(f"Failed to connect to Zerodha API (Check if Access Token is valid for today): {e}")
            logger.warning("Bot will idle until connection is established.")

    def get_historical_data(self, symbol, timeframe):
        """Fetches intraday historical OHLCV data from Zerodha and converts to Pandas DataFrame."""
        if not self.connected:
            self.connect()
            if not self.connected:
                return None

        try:
            # We must use yfinance for commodities by default as the Zerodha historical API requires specific tokens we might not have dynamically
            raise Exception("Using yfinance fallback for Commodities.")
        except Exception as e:
            logger.error("Falling back to yfinance for historical data.")
            try:
                import yfinance as yf
                yf_symbol = "CL=F"
                yf_tf = "1m" if timeframe == "1min" else timeframe.replace("min", "m")
                df = yf.download(yf_symbol, period='5d', interval=yf_tf, progress=False)
                if df is not None and not df.empty:
                    if isinstance(df.columns, pd.MultiIndex):
                        df.columns = df.columns.droplevel(1)
                    df = df.rename(columns={'Open': 'open', 'High': 'high', 'Low': 'low', 'Close': 'close', 'Volume': 'volume'})
                    return df
                else:
                    logger.error("yfinance fallback also returned no data.")
                    return None
            except Exception as yf_e:
                logger.error(f"yfinance fallback failed: {yf_e}")
                return None

    def get_current_future_symbol(self, base_symbol):
        """Fetches the nearest expiry Futures contract for the given commodity."""
        if not self.connected:
            return None

        try:
            if self.instruments_cache is None:
                self.instruments_cache = self.kite.instruments("MCX")

            # Filter for specific symbol and type
            valid_futures = [
                inst for inst in self.instruments_cache
                if inst['name'] == base_symbol and inst['instrument_type'] == "FUT"
            ]

            if not valid_futures:
                return None

            # Sort by expiry date to get the front month
            valid_futures.sort(key=lambda x: x['expiry'])
            nearest_contract = valid_futures[0]

            # Use dynamic lot size
            global LOT_SIZE
            LOT_SIZE = nearest_contract['lot_size']

            return nearest_contract['tradingsymbol']

        except Exception as e:
            logger.error(f"Failed to fetch future symbol: {e}")
            return None

    def get_ltp(self, symbol):
        """Fetches Last Traded Price (LTP)."""
        if not self.connected:
            self.connect()
            if not self.connected:
                return 0.0

        try:
            exchange_symbol = f"MCX:{symbol}"
            response = self.kite.ltp([exchange_symbol])
            return response[exchange_symbol]['last_price']
        except Exception as e:
            logger.error(f"Failed fetching LTP for {symbol}: {e}")
            # Raise the exception so the trade loop can abort instead of proceeding with fake data
            raise e


            # Sort by expiry date and get the closest one
            valid_options.sort(key=lambda x: x['expiry'])
            best_option = valid_options[0]

            return best_option['tradingsymbol'], best_option['lot_size']

        except Exception as e:
            logger.warning(f"Failed to fetch option symbol: {e}")
            return None, None

    def place_order(self, symbol, side, qty, order_type="MARKET", price=0.0):
        if PAPER_TRADING:
            logger.warning(f"[PAPER TRADE] {side} {qty} {symbol} @ {order_type}")
            return f"PAPER_ORDER_{int(time.time())}"
        else:
            if not self.connected:
                logger.error("Cannot place live order. Not connected to broker.")
                return None

            logger.info(f"Placing LIVE {side} order for {qty} of {symbol} at {order_type}")

            # Map 'BUY'/'SELL' to Zerodha constants
            txn_type = self.kite.TRANSACTION_TYPE_BUY if side.upper() == "BUY" else self.kite.TRANSACTION_TYPE_SELL

            # Zerodha blocks raw MARKET orders for NFO. We must convert MARKET to an aggressive LIMIT order.
            if order_type.upper() == "MARKET":
                ord_type = self.kite.ORDER_TYPE_LIMIT
                try:
                    ltp = self.get_ltp(symbol)
                    # Add 2% buffer for buy, subtract 2% for sell to ensure instant execution
                    buffer_pct = 1.02 if side.upper() == "BUY" else 0.98
                    aggressive_price = ltp * buffer_pct
                    # Round to nearest 1.0 (NSE MCX tick size)
                    price = round(aggressive_price / 1.0) * 1.0
                    logger.info(f"Converted MARKET to aggressive LIMIT order at ₹{price:.2f} (LTP was ₹{ltp})")
                except Exception as e:
                    logger.error(f"Failed to fetch LTP for aggressive limit conversion: {e}")
                    return None
            else:
                ord_type = self.kite.ORDER_TYPE_LIMIT

            try:
                order_id = self.kite.place_order(
                    variety=self.kite.VARIETY_REGULAR,
                    exchange=self.kite.EXCHANGE_MCX,
                    tradingsymbol=symbol,
                    transaction_type=txn_type,
                    quantity=qty,
                    product=self.kite.PRODUCT_MIS, # Intraday
                    order_type=ord_type,
                    price=price
                )
                logger.info(f"Live order placed successfully. Order ID: {order_id}")
                return order_id
            except Exception as e:
                logger.error(f"Error placing order via Zerodha: {e}")
                return None

    def get_pnl(self):
        """Fetches today's total realized/unrealized MTM from Zerodha."""
        if not self.connected or PAPER_TRADING:
            return 0.0

        try:
            positions = self.kite.positions()
            net_positions = positions.get('net', [])
            total_mtm = sum(float(pos.get('m2m', 0.0)) for pos in net_positions)
            return total_mtm
        except Exception as e:
            logger.error(f"Error fetching PnL: {e}")
            return 0.0

    def get_balance(self):
        """Fetches available capital from Zerodha."""
        if not self.connected or PAPER_TRADING:
            return 50000.0  # Default mock capital for paper trading

        try:
            margins = self.kite.margins()
            return float(margins.get('equity', {}).get('available', {}).get('live_balance', 50000.0))
        except Exception as e:
            logger.error(f"Error fetching Balance: {e}")
            return 50000.0

# ==========================================
# RISK MANAGEMENT MODULE
# ==========================================
class RiskManager:
    def __init__(self, broker: BrokerAPI):
        self.broker = broker
        self.daily_pnl = 0.0
        self.kill_switch_active = False

        # Dynamic Kill Switch calculation based on opening balance
        self.starting_capital = self.broker.get_balance()
        if self.starting_capital < 100000:
            self.max_loss_limit = -10000.0
        else:
            self.max_loss_limit = -15000.0

    def check_kill_switch(self, current_floating_pnl=0.0):
        """Checks if the daily max loss limit has been hit, including floating MTM."""
        if self.kill_switch_active:
            return True

        # In Paper Trading, the Risk Manager should track the mocked internal daily_realized_pnl.
        # In Live Trading, we can either check the broker MTM, or use our internally tracked realized PNL.
        # For simplicity and accuracy in preventing desync with broker API lags, we will use the bot's internal tracking for both.

        # Add the floating pnl to the realized daily pnl
        total_pnl = self.daily_pnl + current_floating_pnl

        if total_pnl <= self.max_loss_limit:
            logger.error(f"KILL SWITCH TRIGGERED! Max Loss limit of {self.max_loss_limit} reached. Total MTM: {total_pnl}")
            self.kill_switch_active = True
            return True
        return False

    def calculate_sl(self, entry_price, sl_pct):
        """Calculates initial Stop Loss."""
        sl_price = entry_price * (1 - sl_pct)
        return sl_price

    def update_trailing_take_profit(self, current_price, current_sl, max_price_seen, trailing_pct):
        """Calculates Trailing Take Profit (TTP) locking in gains."""
        potential_new_sl = max_price_seen * (1 - trailing_pct)
        if potential_new_sl > current_sl:
            return potential_new_sl
        return current_sl

# ==========================================
# STRATEGY LOGIC
# ==========================================
class ScalpingStrategy:
    def __init__(self, broker: BrokerAPI):
        self.broker = broker
        self.risk_manager = RiskManager(broker)
        self.in_position = False
        self.current_position = None  # 'CE' or 'PE'
        self.entry_price = 0.0
        self.current_sl = 0.0
        self.option_symbol = ""
        self.last_heartbeat_time = datetime.now()
        self.last_pnl_heartbeat_time = datetime.now()
        self.last_fetch_time = None
        self.cached_market_data = None
        self.daily_realized_pnl = 0.0

    def fetch_and_calculate_indicators(self):
        """Fetches data and calculates Rolling High/Low, VWAP, EMA, ADX."""
        # Rate Limiting: Only fetch historical data once every 60 seconds
        now = datetime.now()
        if self.last_fetch_time and (now - self.last_fetch_time).total_seconds() < 60:
            if self.cached_market_data:
                try:
                    # Update only the current close price (LTP) for precise breakout detection
                    self.cached_market_data['close'] = self.broker.get_ltp(SYMBOL)
                except Exception as e:
                    logger.warning(f"Error updating live index price: {e}")
                return self.cached_market_data
            return None # Strict rate limit enforcement if cache is empty

        df = self.broker.get_historical_data(SYMBOL, TIMEFRAME)

        # Always update the fetch time so we don't spam the API on failure
        self.last_fetch_time = now

        if df is None or len(df) < 50:
            return None

        # Assuming 'df' has columns: datetime, open, high, low, close, volume
        # 1. Rolling 30-Minute High / Low (30 candles on 1min chart)
        # Exclude the current live, unclosed candle (-1)
        # Ensure we don't mix previous day's data during the first 30 minutes of a gap open
        today_date = datetime.now().date()
        today_mask = df.index.date == today_date
        today_df = df[today_mask]

        if len(today_df) > 1:
            # We have at least some closed candles today
            rolling_data = today_df.iloc[-31:-1]
            rolling_high = rolling_data['high'].max()
            rolling_low = rolling_data['low'].min()
        else:
            # Not enough data for today yet (e.g. first candle of the day is forming)
            # Fallback to previous 30 candles, though trades are unlikely this early
            rolling_data = df.iloc[-31:-1]
            rolling_high = rolling_data['high'].max()
            rolling_low = rolling_data['low'].min()

        # 2. Indicators (using ta)
        df[f'EMA_{EMA_PERIOD}'] = ta.trend.EMAIndicator(close=df['close'], window=EMA_PERIOD).ema_indicator()

        adx_ind = ta.trend.ADXIndicator(high=df['high'], low=df['low'], close=df['close'], window=ADX_PERIOD)
        df[f'ADX_{ADX_PERIOD}'] = adx_ind.adx()
        df['ADX_Slope'] = df[f'ADX_{ADX_PERIOD}'].diff()

        df[f'RSI_{RSI_PERIOD}'] = ta.momentum.RSIIndicator(close=df['close'], window=RSI_PERIOD).rsi()

        # Simplified Intraday VWAP / Fallback
        # We must calculate VWAP only on today's data slice
        df['Typical_Price'] = (df['high'] + df['low'] + df['close']) / 3

        # If the broker returns 0 volume for the index, fallback to cumulative typical price average
        if 'volume' not in df.columns or df.loc[today_mask, 'volume'].sum() == 0:
            df.loc[today_mask, 'VWAP_D'] = df.loc[today_mask, 'Typical_Price'].expanding().mean()
        else:
            df.loc[today_mask, 'Vol_x_Typ'] = df.loc[today_mask, 'volume'] * df.loc[today_mask, 'Typical_Price']
            df.loc[today_mask, 'Cum_Vol'] = df.loc[today_mask, 'volume'].cumsum()
            df.loc[today_mask, 'Cum_Vol_x_Typ'] = df.loc[today_mask, 'Vol_x_Typ'].cumsum()
            df.loc[today_mask, 'VWAP_D'] = df.loc[today_mask, 'Cum_Vol_x_Typ'] / df.loc[today_mask, 'Cum_Vol']

        latest_data = df.iloc[-1]

        # Ensure ADX is populated (requires 28 periods to stabilize)
        if pd.isna(latest_data[f'ADX_{ADX_PERIOD}']) or pd.isna(latest_data['ADX_Slope']) or pd.isna(latest_data[f'RSI_{RSI_PERIOD}']):
            return None

        self.cached_market_data = {
            'timestamp': df.index[-1],
            'close': latest_data['close'],
            'open': latest_data['open'],
            'high': latest_data['high'],
            'low': latest_data['low'],
            'rolling_high': rolling_high,
            'rolling_low': rolling_low,
            'ema': latest_data[f'EMA_{EMA_PERIOD}'],
            'adx': latest_data[f'ADX_{ADX_PERIOD}'],
            'adx_slope': latest_data['ADX_Slope'],
            'rsi': latest_data[f'RSI_{RSI_PERIOD}'],
            'vwap': latest_data['VWAP_D']
        }
        return self.cached_market_data



    def execute_trade(self, opt_type, spot_price, adx_value):
        """Executes the entry order and sets dynamic initial SL."""
        strike = self.get_atm_strike(spot_price)
        self.option_symbol, dynamic_lot_size = self.get_option_symbol(strike, opt_type)

        if not self.option_symbol or not dynamic_lot_size:
            logger.error("Trade Aborted: Could not determine valid option symbol or lot size from broker.")
            return

        # Dynamic Quantity Calculation based on Live Balance (Max 10 Lots)
        live_balance = self.broker.get_balance()
        # Use 95% of available capital
        max_investment = live_balance * 0.95

        # Estimate premium using ~0.5 delta assumption for ATM (just for initial sizing if fetching fails)
        estimated_premium = (spot_price * 0.005)

        # Try to get the actual live premium first to size perfectly
        try:
            live_premium = self.broker.get_ltp(self.option_symbol)
            if live_premium > 0:
                estimated_premium = live_premium
        except Exception:
            pass

        calculated_lots = int(max_investment / (estimated_premium * dynamic_lot_size))
        calculated_lots = min(calculated_lots, 10) # Cap at 10 lots max

        if calculated_lots <= 0:
            logger.error(f"Trade Aborted: Insufficient funds to buy even 1 lot. Balance: {live_balance}")
            return

        trade_qty = calculated_lots * dynamic_lot_size

        # Place Market Order
        order_id = self.broker.place_order(self.option_symbol, "BUY", trade_qty)

        if not order_id:
            logger.error("Trade Aborted: Order placement failed via broker API.")
            return

        # WE ARE NOW IN A LIVE POSITION
        self.in_position = True
        self.current_position = opt_type
        self.current_qty = trade_qty

        try:
            # Fetch Entry Price
            self.entry_price = self.broker.get_ltp(self.option_symbol)
        except Exception as e:
            logger.error(f"Failed to fetch exact entry price after fill - {e}. Falling back to estimated premium.")
            # DO NOT ABORT OR SET IN_POSITION TO FALSE! We already bought it!
            self.entry_price = estimated_premium

        # Dynamic Risk Allocation based on trend strength
        if adx_value >= 30:
            self.trade_sl_pct = 0.08
            self.trade_target_pct = 0.20
            self.trade_trailing_pct = 1.0
            logger.info("Very Strong Trend Detected. Engaging Max Profitability settings.")
        elif adx_value >= ADX_THRESHOLD:
            self.trade_sl_pct = 1.0
            self.trade_target_pct = 0.10
            self.trade_trailing_pct = 0.03
            logger.info("Moderate Trend Detected. Engaging Balanced Scalp settings.")
        else:
            self.trade_sl_pct = 0.03
            self.trade_target_pct = 0.06
            self.trade_trailing_pct = 0.02
            logger.info("Sideways Chop Detected. Engaging tight hit-and-run scalping parameters.")

        # Calculate & System Place SL
        self.current_sl = self.risk_manager.calculate_sl(self.entry_price, self.trade_sl_pct)
        # In reality, place a Stop Loss Market (SL-M) order here with the broker

        self.in_position = True
        self.current_position = opt_type
        self.max_opt_price_seen = self.entry_price
        self.target_reached = False
        self.breakeven_reached = False
        self.last_pnl_heartbeat_time = datetime.now()

        logger.info(f"Entered {opt_type} at {self.entry_price}. Initial SL: {self.current_sl}")

    def exit_trade(self, reason):
        """Exits current position."""
        trade_qty = getattr(self, 'current_qty', LOT_SIZE)

        # If we are LONG (CE), we must SELL to exit. If SHORT (PE), we must BUY to cover.
        exit_direction = "SELL" if self.current_position == "CE" else "BUY"
        self.broker.place_order(self.option_symbol, exit_direction, trade_qty)

        try:
            exit_price = self.broker.get_ltp(self.option_symbol)
        except Exception:
            # Fallback to current SL if fetch fails during exit
            exit_price = self.current_sl

        realized_pnl = (exit_price - self.entry_price) * trade_qty
        self.daily_realized_pnl += realized_pnl

        logger.info(f"Exited position {self.current_position} at {exit_price:.2f}. Reason: {reason}")
        logger.info(f"Trade PNL: ₹{realized_pnl:.2f} | Total Daily PNL: ₹{self.daily_realized_pnl:.2f}")

        self.in_position = False
        self.current_position = None
        self.entry_price = 0.0
        self.current_sl = 0.0

    def manage_open_position(self):
        """Manages Trailing Take Profit, Breakeven SL, and Stop Loss hits."""
        try:
            current_opt_price = self.broker.get_ltp(self.option_symbol)
        except Exception as e:
            logger.warning(f"Error checking open position price: {e}")
            return

        if self.current_position == "CE":
            if current_opt_price > self.max_opt_price_seen:
                self.max_opt_price_seen = current_opt_price
        else:
            if current_opt_price < self.max_opt_price_seen:
                self.max_opt_price_seen = current_opt_price

        trade_qty = getattr(self, 'current_qty', LOT_SIZE)
        if self.current_position == "CE":
            current_floating_pnl = (current_opt_price - self.entry_price) * trade_qty
        else:
            current_floating_pnl = (self.entry_price - current_opt_price) * trade_qty

        # Live PNL Logging
        now = datetime.now()
        if (now - self.last_pnl_heartbeat_time).total_seconds() >= 30: # Log every 30 seconds
            logger.info(f"[LIVE PNL] {self.option_symbol} | LTP: {current_opt_price:.2f} | PNL: ₹{current_floating_pnl:.2f} | SL: {self.current_sl:.2f}")
            self.last_pnl_heartbeat_time = now

        # 0. Floating Kill Switch Hit
        if self.risk_manager.check_kill_switch(current_floating_pnl=current_floating_pnl):
            self.exit_trade("Kill Switch Hit")
            return

        # 1. Check SL / TTP Hit
        if self.current_position == "CE" and current_opt_price <= self.current_sl:
            reason = "Trailing Take Profit Hit" if self.target_reached else ("Break Even Hit" if self.breakeven_reached else "Stop Loss Hit")
            self.exit_trade(reason)
            return
        elif self.current_position == "PE" and current_opt_price >= self.current_sl:
            reason = "Trailing Take Profit Hit" if self.target_reached else ("Break Even Hit" if self.breakeven_reached else "Stop Loss Hit")
            self.exit_trade(reason)
            return

        if self.current_position == "CE":
            points_gained = current_opt_price - self.entry_price
        else:
            points_gained = self.entry_price - current_opt_price

        # 2. Update Trailing Take Profit (Target Reached)
        if points_gained >= self.trade_target_points:
            if not self.target_reached:
                logger.info(f"Target Reached! Activating Trailing Take Profit.")
                self.target_reached = True

            if self.current_position == "CE":
                new_sl = self.max_opt_price_seen - self.trade_trailing_points
                if new_sl > self.current_sl:
                    self.current_sl = new_sl
            else:
                new_sl = self.max_opt_price_seen + self.trade_trailing_points
                if new_sl < self.current_sl:
                    self.current_sl = new_sl

        # 3. Update to Break Even (1:1 RR Reached)
        elif points_gained >= self.trade_sl_points and not self.target_reached and not self.breakeven_reached:
            self.breakeven_reached = True
            if self.current_position == "CE":
                self.current_sl = self.entry_price + (TICK_SIZE * 5) # Slightly above entry to cover fees
            else:
                self.current_sl = self.entry_price - (TICK_SIZE * 5)
            logger.info(f"1:1 R:R Reached. Moving SL to Break Even: {self.current_sl:.2f}")

        # 4. Continuous Step Trailing (Between Break-Even and Target)
        elif self.breakeven_reached and not self.target_reached:
            if self.current_position == "CE":
                new_sl = self.max_opt_price_seen - self.trade_trailing_points
                if new_sl > self.current_sl:
                    self.current_sl = new_sl
            else:
                new_sl = self.max_opt_price_seen + self.trade_trailing_points
                if new_sl < self.current_sl:
                    self.current_sl = new_sl

    def run_cycle(self):
        """Main strategy loop executed every tick/candle."""
        # Sync internally tracked realized PNL to risk manager for the kill switch
        self.risk_manager.daily_pnl = self.daily_realized_pnl

        if self.risk_manager.check_kill_switch():
            if self.in_position:
                self.exit_trade("Kill Switch Triggered")
            return

        # Fetch market data and indicators
        market_data = self.fetch_and_calculate_indicators()

        now = datetime.now()

        if not market_data:
            if (now - self.last_heartbeat_time).total_seconds() >= 300:
                logger.info(f"[HEARTBEAT] Bot is alive. Waiting for valid market data...")
                self.last_heartbeat_time = now
            return

        timestamp = market_data['timestamp']
        close_price = market_data['close']
        open_price = market_data['open']
        high_price = market_data['high']
        low_price = market_data['low']
        r_high = market_data['rolling_high']
        r_low = market_data['rolling_low']
        ema = market_data['ema']
        vwap = market_data['vwap']
        adx = market_data['adx']
        adx_slope = market_data['adx_slope']
        rsi = market_data['rsi']

        if self.in_position:
            self.manage_open_position()
            return

        # ==========================================
        # FILTERS & ENTRY LOGIC
        # ==========================================
        current_reason = "Waiting for setup."

        # ==========================================
        # STRATEGY 1: SIDEWAYS / CHOPPY MARKET
        # ==========================================
        if adx < ADX_THRESHOLD:
            # Supply & Demand Scalping (Mean-Reversion off extremes)
            if low_price <= r_low and close_price > r_low and rsi < 45:
                logger.info("Demand Zone Rejection Detected (Sideways Market).")
                self.execute_trade("CE", close_price, adx)
                return
            elif high_price >= r_high and close_price < r_high and rsi > 55:
                logger.info("Supply Zone Rejection Detected (Sideways Market).")
                self.execute_trade("PE", close_price, adx)
                return

            current_reason = f"Sideways Market (ADX {adx:.2f} < {ADX_THRESHOLD}). Waiting for Supply/Demand touch."

        else:
            # ==========================================
            # STRATEGY 2: MOMENTUM / TRENDING MARKET
            # ==========================================
            # Chop Killer: Ensure price is expanding away from VWAP
            vwap_distance_pct = abs(close_price - vwap) / vwap

            # Determine if we are in the market open period (first 45 mins)
            market_open_time = timestamp.replace(hour=9, minute=15, second=0, microsecond=0)
            time_since_open = timestamp - market_open_time
            is_market_open_period = time_since_open.total_seconds() <= 45 * 60

            if vwap_distance_pct <= 0.0005 and not is_market_open_period:
                current_reason = f"Price too close to VWAP (Chop Zone)"

            else:
                # 1. Breakout Strategy
                # Long CE: Price breaks Rolling High AND Price is expanding above VWAP/EMA AND RSI > 50
                if close_price > r_high and close_price > vwap and close_price > ema and rsi > 50:
                    logger.info("Bullish Breakout Detected.")
                    self.execute_trade("CE", close_price, adx)
                    return

                # Long PE: Price breaks Rolling Low AND Price is expanding below VWAP/EMA AND RSI < 50
                elif close_price < r_low and close_price < vwap and close_price < ema and rsi < 50:
                    logger.info("Bearish Breakdown Detected.")
                    self.execute_trade("PE", close_price, adx)
                    return

                # 2. Mean-Reversion Strategy
                # Bullish Rejection: Wick poked below rolling low, closed above, in an uptrend, RSI > 50
                elif low_price < r_low and close_price > r_low and close_price > open_price and close_price > vwap and close_price > ema and rsi > 50:
                    logger.info("Bullish Mean-Rejection Detected.")
                    self.execute_trade("CE", close_price, adx)
                    return

                # Bearish Rejection: Wick poked above rolling high, closed below, in a downtrend, RSI < 50
                elif high_price > r_high and close_price < r_high and close_price < open_price and close_price < vwap and close_price < ema and rsi < 50:
                    logger.info("Bearish Mean-Rejection Detected.")
                    self.execute_trade("PE", close_price, adx)
                    return

                else:
                    if close_price <= r_high and close_price >= r_low:
                        current_reason = "Price is trapped inside 30-min Rolling Range"
                    elif rsi <= 50 and close_price > vwap:
                        current_reason = "Price is bullish, but RSI < 50 does not confirm momentum"
                    elif rsi >= 50 and close_price < vwap:
                        current_reason = "Price is bearish, but RSI > 50 does not confirm momentum"
                    else:
                        current_reason = "Awaiting convergence of VWAP, EMA, and Breakout levels"

        # --- Heartbeat Logging ---
        # Print a status update every 5 minutes so the user knows what the bot is thinking
        if (now - self.last_heartbeat_time).total_seconds() >= 300: # 300 seconds = 5 mins
            logger.info(f"[HEARTBEAT] {SYMBOL} LTP: {close_price:.2f} | ADX: {adx:.2f} | RSI: {rsi:.2f}")
            logger.info(f"[STATUS] Skipping Trade: {current_reason}")
            self.last_heartbeat_time = now
        # -------------------------

# ==========================================
# MAIN EXECUTION
# ==========================================
if __name__ == "__main__":
    broker = BrokerAPI()
    bot = ScalpingStrategy(broker)

    logger.info("Starting Options Scalping Bot...")

    try:
        while True:
            now = datetime.now().time()

            # MCX Intraday strict timings (09:00 AM to 11:30 PM)
            # We square off everything by 23:15 to prevent overnight holding
            start_time = datetime.strptime("09:00", "%H:%M").time()
            mis_square_off_time = datetime.strptime("23:15", "%H:%M").time()

            if start_time <= now < mis_square_off_time:
                bot.run_cycle()

            elif now >= mis_square_off_time:
                if bot.in_position:
                    logger.warning("MIS Square Off Time Reached (23:15). Closing all open intraday positions!")
                    bot.exit_trade("MIS Auto Square Off (23:15)")

                # If market is fully closed, exit loop
                if now > datetime.strptime("23:30", "%H:%M").time() or now < start_time:
                    logger.info("Market Closed for the day. Exiting.")
                    logger.info(f"===================================")
                    logger.info(f"FINAL DAILY PNL: ₹{bot.daily_realized_pnl:.2f}")
                    logger.info(f"===================================")
                    break

            # Wait for next cycle
            time.sleep(1)

    except KeyboardInterrupt:
        logger.info("Bot stopped manually.")
        if bot.in_position:
            bot.exit_trade("Manual Stop")
        logger.info(f"===================================")
        logger.info(f"FINAL DAILY PNL: ₹{bot.daily_realized_pnl:.2f}")
        logger.info(f"===================================")
