import time
import logging
import pandas as pd
import ta
from datetime import datetime, timedelta

# ==========================================
# CONFIGURATION & PARAMETERS
# ==========================================
SYMBOL = "NIFTY"
TIMEFRAME = "1min"  # 1-minute timeframe for hyper-scalping

# Risk Management
# Quantity and Max Loss are calculated dynamically based on live broker balance

# Trend & Momentum Filters
EMA_PERIOD = 21
ADX_PERIOD = 14
ADX_THRESHOLD = 20
RSI_PERIOD = 14

# Mode Setup
PAPER_TRADING = True  # Set to False ONLY when ready to risk real capital

# Logging Setup
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# ==========================================
# BROKER INTERFACE (Zerodha KiteConnect Integration)
# ==========================================
try:
    from kiteconnect import KiteConnect
except ImportError:
    logger.error("kiteconnect library not found. Run: pip install kiteconnect")

class BrokerAPI:
    """Live integration with Zerodha KiteConnect API."""
    def __init__(self):
        import os
        # ---------------------------------------------------------
        # TODO: Replace with your actual Zerodha API Key
        # Note: The Access Token is loaded automatically from access_token.txt
        # (Generated by running zerodha_login.py)
        # ---------------------------------------------------------
        self.api_key = "YOUR_ZERODHA_API_KEY"
        self.instruments_cache = None

        self.connect()

    def connect(self):
        """Attempts to establish connection with Zerodha API."""
        import os

        if not os.path.exists("access_token.txt"):
            logger.error("access_token.txt not found! Please run `python zerodha_login.py` first to authenticate for the day.")
            self.connected = False
            return

        with open("access_token.txt", "r") as f:
            access_token = f.read().strip()

        try:
            self.kite = KiteConnect(api_key=self.api_key)
            self.kite.set_access_token(access_token)

            # Simple ping to profile to verify token is valid
            self.kite.profile()

            self.connected = True
            logger.info(f"Zerodha Broker Connected Successfully. Paper Trading Mode: {PAPER_TRADING}")
        except Exception as e:
            self.connected = False
            logger.error(f"Failed to connect to Zerodha API (Check if Access Token is valid for today): {e}")
            logger.warning("Bot will idle until connection is established.")

    def get_historical_data(self, symbol, timeframe):
        """Fetches intraday historical OHLCV data from Zerodha and converts to Pandas DataFrame."""
        if not self.connected:
            self.connect()
            if not self.connected:
                return None

        try:
            # Zerodha requires the instrument token for historical data.
            # Nifty 50 Index Instrument Token is generally 256265
            instrument_token = 256265

            # Map timeframe string to Zerodha's format
            tf_map = {"1min": "minute", "3min": "3minute", "5min": "5minute", "15min": "15minute"}
            kite_tf = tf_map.get(timeframe, "minute")

            # Fetch 3 days of data to give EMA and RSI enough runway to stabilize and avoid NaNs
            from_date = (datetime.now() - timedelta(days=3)).replace(hour=9, minute=15, second=0, microsecond=0)
            to_date = datetime.now()

            records = self.kite.historical_data(
                instrument_token=instrument_token,
                from_date=from_date,
                to_date=to_date,
                interval=kite_tf
            )

            if records:
                df = pd.DataFrame(records)
                # Ensure correct column naming for the strategy
                df = df.rename(columns={'date': 'datetime'})
                df.set_index('datetime', inplace=True)
                return df
            else:
                logger.error("No historical data returned from Zerodha.")
                return None
        except Exception as e:
            logger.error(f"Error fetching historical data: {e}")
            return None

    def get_ltp(self, symbol):
        """Fetches Last Traded Price (LTP)."""
        if not self.connected:
            self.connect()
            if not self.connected:
                return 0.0

        try:
            # Index spot price is on the NSE, options are on NFO
            if symbol == "NIFTY":
                exchange_symbol = "NSE:NIFTY 50"
            elif symbol == "BANKNIFTY":
                exchange_symbol = "NSE:NIFTY BANK"
            else:
                # Zerodha requires the exchange prefix for LTP (e.g., NFO:NIFTY24MAY22000CE)
                exchange_symbol = f"NFO:{symbol}"

            response = self.kite.ltp([exchange_symbol])
            return response[exchange_symbol]['last_price']
        except Exception as e:
            logger.error(f"Failed fetching LTP for {symbol}: {e}")
            # Raise the exception so the trade loop can abort instead of proceeding with fake data
            raise e

    def get_real_option_symbol(self, index_symbol, strike, opt_type):
        """Fetches the nearest expiry option symbol for the given index, strike, and type."""
        if not self.connected:
            return None

        try:
            if self.instruments_cache is None:
                logger.info("Fetching instruments from Zerodha...")
                self.instruments_cache = self.kite.instruments("NFO")

            # Filter for the specific index and strike
            valid_options = [
                inst for inst in self.instruments_cache
                if inst['name'] == index_symbol and
                inst['strike'] == float(strike) and
                inst['instrument_type'] == opt_type
            ]

            if not valid_options:
                logger.error(f"No valid option found for {index_symbol} {strike} {opt_type}")
                return None

            # Sort by expiry date and get the closest one
            valid_options.sort(key=lambda x: x['expiry'])
            return valid_options[0]['tradingsymbol']

        except Exception as e:
            logger.warning(f"Failed to fetch option symbol: {e}")
            return None

    def place_order(self, symbol, side, qty, order_type="MARKET", price=0.0):
        if PAPER_TRADING:
            logger.warning(f"[PAPER TRADE] {side} {qty} {symbol} @ {order_type}")
            return f"PAPER_ORDER_{int(time.time())}"
        else:
            if not self.connected:
                logger.error("Cannot place live order. Not connected to broker.")
                return None

            logger.info(f"Placing LIVE {side} order for {qty} of {symbol} at {order_type}")

            # Map 'BUY'/'SELL' to Zerodha constants
            txn_type = self.kite.TRANSACTION_TYPE_BUY if side.upper() == "BUY" else self.kite.TRANSACTION_TYPE_SELL
            ord_type = self.kite.ORDER_TYPE_MARKET if order_type.upper() == "MARKET" else self.kite.ORDER_TYPE_LIMIT

            try:
                order_id = self.kite.place_order(
                    variety=self.kite.VARIETY_REGULAR,
                    exchange=self.kite.EXCHANGE_NFO,
                    tradingsymbol=symbol,
                    transaction_type=txn_type,
                    quantity=qty,
                    product=self.kite.PRODUCT_MIS, # Intraday
                    order_type=ord_type,
                    price=price
                )
                logger.info(f"Live order placed successfully. Order ID: {order_id}")
                return order_id
            except Exception as e:
                logger.error(f"Error placing order via Zerodha: {e}")
                return None

    def get_pnl(self):
        """Fetches today's total realized/unrealized MTM from Zerodha."""
        if not self.connected or PAPER_TRADING:
            return 0.0

        try:
            positions = self.kite.positions()
            net_positions = positions.get('net', [])
            total_mtm = sum(float(pos.get('m2m', 0.0)) for pos in net_positions)
            return total_mtm
        except Exception as e:
            logger.error(f"Error fetching PnL: {e}")
            return 0.0

    def get_balance(self):
        """Fetches available capital from Zerodha."""
        if not self.connected or PAPER_TRADING:
            return 50000.0  # Default mock capital for paper trading

        try:
            margins = self.kite.margins()
            return float(margins.get('equity', {}).get('available', {}).get('live_balance', 50000.0))
        except Exception as e:
            logger.error(f"Error fetching Balance: {e}")
            return 50000.0

# ==========================================
# RISK MANAGEMENT MODULE
# ==========================================
class RiskManager:
    def __init__(self, broker: BrokerAPI):
        self.broker = broker
        self.daily_pnl = 0.0
        self.kill_switch_active = False

        # Dynamic Kill Switch calculation based on opening balance
        self.starting_capital = self.broker.get_balance()
        if self.starting_capital < 100000:
            self.max_loss_limit = -10000.0
        else:
            self.max_loss_limit = -15000.0

    def check_kill_switch(self):
        """Checks if the daily max loss limit has been hit."""
        if self.kill_switch_active:
            return True

        # In Paper Trading, the Risk Manager should track the mocked internal daily_realized_pnl
        # In Live Trading, it checks the actual broker MTM
        if PAPER_TRADING:
            # We will rely on the ScalpingStrategy to inject the daily_realized_pnl here later in the main loop
            pass
        else:
            self.daily_pnl = self.broker.get_pnl()

        if self.daily_pnl <= self.max_loss_limit:
            logger.error(f"KILL SWITCH TRIGGERED! Max Loss limit of {self.max_loss_limit} reached. Daily PnL: {self.daily_pnl}")
            self.kill_switch_active = True
            return True
        return False

    def calculate_sl(self, entry_price, sl_pct):
        """Calculates initial Stop Loss."""
        sl_price = entry_price * (1 - sl_pct)
        return sl_price

    def update_trailing_take_profit(self, current_price, current_sl, max_price_seen, trailing_pct):
        """Calculates Trailing Take Profit (TTP) locking in gains."""
        potential_new_sl = max_price_seen * (1 - trailing_pct)
        if potential_new_sl > current_sl:
            return potential_new_sl
        return current_sl

# ==========================================
# STRATEGY LOGIC
# ==========================================
class ScalpingStrategy:
    def __init__(self, broker: BrokerAPI):
        self.broker = broker
        self.risk_manager = RiskManager(broker)
        self.in_position = False
        self.current_position = None  # 'CE' or 'PE'
        self.entry_price = 0.0
        self.current_sl = 0.0
        self.option_symbol = ""
        self.last_heartbeat_time = datetime.now()
        self.last_pnl_heartbeat_time = datetime.now()
        self.last_fetch_time = None
        self.cached_market_data = None
        self.daily_realized_pnl = 0.0

    def fetch_and_calculate_indicators(self):
        """Fetches data and calculates Rolling High/Low, VWAP, EMA, ADX."""
        # Rate Limiting: Only fetch historical data once every 60 seconds
        now = datetime.now()
        if self.last_fetch_time and (now - self.last_fetch_time).total_seconds() < 60:
            if self.cached_market_data:
                try:
                    # Update only the current close price (LTP) for precise breakout detection
                    self.cached_market_data['close'] = self.broker.get_ltp(SYMBOL)
                except Exception as e:
                    logger.warning(f"Error updating live index price: {e}")
                return self.cached_market_data

        df = self.broker.get_historical_data(SYMBOL, TIMEFRAME)
        if df is None or len(df) < 50:
            return None

        self.last_fetch_time = now

        # Assuming 'df' has columns: datetime, open, high, low, close, volume
        # 1. Rolling 30-Minute High / Low (30 candles on 1min chart)
        # Exclude the current live, unclosed candle (-1)
        # Ensure we don't mix previous day's data during the first 30 minutes of a gap open
        today_date = datetime.now().date()
        today_mask = df.index.date == today_date
        today_df = df[today_mask]

        if len(today_df) > 1:
            # We have at least some closed candles today
            rolling_data = today_df.iloc[-31:-1]
            rolling_high = rolling_data['high'].max()
            rolling_low = rolling_data['low'].min()
        else:
            # Not enough data for today yet (e.g. first candle of the day is forming)
            # Fallback to previous 30 candles, though trades are unlikely this early
            rolling_data = df.iloc[-31:-1]
            rolling_high = rolling_data['high'].max()
            rolling_low = rolling_data['low'].min()

        # 2. Indicators (using ta)
        df[f'EMA_{EMA_PERIOD}'] = ta.trend.EMAIndicator(close=df['close'], window=EMA_PERIOD).ema_indicator()

        adx_ind = ta.trend.ADXIndicator(high=df['high'], low=df['low'], close=df['close'], window=ADX_PERIOD)
        df[f'ADX_{ADX_PERIOD}'] = adx_ind.adx()
        df['ADX_Slope'] = df[f'ADX_{ADX_PERIOD}'].diff()

        df[f'RSI_{RSI_PERIOD}'] = ta.momentum.RSIIndicator(close=df['close'], window=RSI_PERIOD).rsi()

        # Simplified Intraday VWAP / Fallback
        # We must calculate VWAP only on today's data slice
        df['Typical_Price'] = (df['high'] + df['low'] + df['close']) / 3

        # If the broker returns 0 volume for the index, fallback to cumulative typical price average
        if 'volume' not in df.columns or df.loc[today_mask, 'volume'].sum() == 0:
            df.loc[today_mask, 'VWAP_D'] = df.loc[today_mask, 'Typical_Price'].expanding().mean()
        else:
            df.loc[today_mask, 'Vol_x_Typ'] = df.loc[today_mask, 'volume'] * df.loc[today_mask, 'Typical_Price']
            df.loc[today_mask, 'Cum_Vol'] = df.loc[today_mask, 'volume'].cumsum()
            df.loc[today_mask, 'Cum_Vol_x_Typ'] = df.loc[today_mask, 'Vol_x_Typ'].cumsum()
            df.loc[today_mask, 'VWAP_D'] = df.loc[today_mask, 'Cum_Vol_x_Typ'] / df.loc[today_mask, 'Cum_Vol']

        latest_data = df.iloc[-1]

        # Ensure ADX is populated (requires 28 periods to stabilize)
        if pd.isna(latest_data[f'ADX_{ADX_PERIOD}']) or pd.isna(latest_data['ADX_Slope']) or pd.isna(latest_data[f'RSI_{RSI_PERIOD}']):
            return None

        self.cached_market_data = {
            'timestamp': df.index[-1],
            'close': latest_data['close'],
            'open': latest_data['open'],
            'high': latest_data['high'],
            'low': latest_data['low'],
            'rolling_high': rolling_high,
            'rolling_low': rolling_low,
            'ema': latest_data[f'EMA_{EMA_PERIOD}'],
            'adx': latest_data[f'ADX_{ADX_PERIOD}'],
            'adx_slope': latest_data['ADX_Slope'],
            'rsi': latest_data[f'RSI_{RSI_PERIOD}'],
            'vwap': latest_data['VWAP_D']
        }
        return self.cached_market_data

    def get_atm_strike(self, spot_price):
        """Calculates At-The-Money (ATM) strike."""
        return round(spot_price / 50) * 50

    def get_option_symbol(self, strike, opt_type):
        """Constructs option trading symbol. (Format depends on broker)"""
        return self.broker.get_real_option_symbol(SYMBOL, strike, opt_type)

    def execute_trade(self, opt_type, spot_price, adx_value):
        """Executes the entry order and sets dynamic initial SL."""
        strike = self.get_atm_strike(spot_price)
        self.option_symbol = self.get_option_symbol(strike, opt_type)

        if not self.option_symbol:
            logger.error("Trade Aborted: Could not determine valid option symbol. Make sure Kite API is connected and active.")
            return

        # Dynamic Quantity Calculation based on Live Balance (Max 10 Lots)
        live_balance = self.broker.get_balance()
        # Use 95% of available capital
        max_investment = live_balance * 0.95

        # Estimate premium using ~0.5 delta assumption for ATM (just for initial sizing if fetching fails)
        # Nifty Lot Size is 50
        estimated_premium = (spot_price * 0.005)

        # Try to get the actual live premium first to size perfectly
        try:
            live_premium = self.broker.get_ltp(self.option_symbol)
            if live_premium > 0:
                estimated_premium = live_premium
        except Exception:
            pass

        calculated_lots = int(max_investment / (estimated_premium * 50))
        calculated_lots = min(calculated_lots, 10) # Cap at 10 lots (500 qty)

        if calculated_lots <= 0:
            logger.error(f"Trade Aborted: Insufficient funds to buy even 1 lot. Balance: {live_balance}")
            return

        trade_qty = calculated_lots * 50

        # Place Market Order
        order_id = self.broker.place_order(self.option_symbol, "BUY", trade_qty)

        if not order_id:
            logger.error("Trade Aborted: Order placement failed via broker API.")
            return

        # WE ARE NOW IN A LIVE POSITION
        self.in_position = True
        self.current_position = opt_type
        self.current_qty = trade_qty

        try:
            # Fetch Entry Price
            self.entry_price = self.broker.get_ltp(self.option_symbol)
        except Exception as e:
            logger.error(f"Failed to fetch exact entry price after fill - {e}. Falling back to estimated premium.")
            # DO NOT ABORT OR SET IN_POSITION TO FALSE! We already bought it!
            self.entry_price = estimated_premium

        # Dynamic Risk Allocation based on trend strength
        if adx_value >= 30:
            self.trade_sl_pct = 0.08
            self.trade_target_pct = 0.20
            self.trade_trailing_pct = 0.05
            logger.info("Very Strong Trend Detected. Engaging Max Profitability settings.")
        elif adx_value >= ADX_THRESHOLD:
            self.trade_sl_pct = 0.05
            self.trade_target_pct = 0.10
            self.trade_trailing_pct = 0.03
            logger.info("Moderate Trend Detected. Engaging Balanced Scalp settings.")
        else:
            self.trade_sl_pct = 0.03
            self.trade_target_pct = 0.06
            self.trade_trailing_pct = 0.02
            logger.info("Sideways Chop Detected. Engaging tight hit-and-run scalping parameters.")

        # Calculate & System Place SL
        self.current_sl = self.risk_manager.calculate_sl(self.entry_price, self.trade_sl_pct)
        # In reality, place a Stop Loss Market (SL-M) order here with the broker

        self.in_position = True
        self.current_position = opt_type
        self.max_opt_price_seen = self.entry_price
        self.target_reached = False
        self.breakeven_reached = False
        self.is_sideways = True if adx_value < ADX_THRESHOLD else False
        self.last_pnl_heartbeat_time = datetime.now()

        # Sideways specific INR trailing
        self.sideways_pnl_milestone = 1000.0
        self.sideways_pnl_lock_amount = 500.0

        logger.info(f"Entered {opt_type} at {self.entry_price}. Initial SL: {self.current_sl}")

    def exit_trade(self, reason):
        """Exits current position."""
        trade_qty = getattr(self, 'current_qty', 500)
        self.broker.place_order(self.option_symbol, "SELL", trade_qty)

        try:
            exit_price = self.broker.get_ltp(self.option_symbol)
        except Exception:
            # Fallback to current SL if fetch fails during exit
            exit_price = self.current_sl

        realized_pnl = (exit_price - self.entry_price) * trade_qty
        self.daily_realized_pnl += realized_pnl

        logger.info(f"Exited position {self.current_position} at {exit_price:.2f}. Reason: {reason}")
        logger.info(f"Trade PNL: ₹{realized_pnl:.2f} | Total Daily PNL: ₹{self.daily_realized_pnl:.2f}")

        self.in_position = False
        self.current_position = None
        self.entry_price = 0.0
        self.current_sl = 0.0

    def manage_open_position(self):
        """Manages Trailing Take Profit, Breakeven SL, and Stop Loss hits."""
        try:
            current_opt_price = self.broker.get_ltp(self.option_symbol)
        except Exception as e:
            logger.warning(f"Error checking open position price: {e}")
            return

        if current_opt_price > self.max_opt_price_seen:
            self.max_opt_price_seen = current_opt_price

        trade_qty = getattr(self, 'current_qty', 500)
        current_floating_pnl = (current_opt_price - self.entry_price) * trade_qty

        # Sideways Market INR Step-Trailing
        # If we are in chop mode, lock in 500 rupees for every 1000 gained
        if getattr(self, 'is_sideways', False):
            if current_floating_pnl >= self.sideways_pnl_milestone:
                # Calculate the exact price needed to guarantee the lock_amount
                locked_price = self.entry_price + (self.sideways_pnl_lock_amount / trade_qty)
                if locked_price > self.current_sl:
                    logger.info(f"Sideways INR Milestone Hit (+₹{self.sideways_pnl_milestone}). Locking in ₹{self.sideways_pnl_lock_amount} profit.")
                    self.current_sl = locked_price
                # Increment the milestone for the next jump (e.g. 1500, 2000)
                self.sideways_pnl_milestone += 500.0
                self.sideways_pnl_lock_amount += 500.0
                self.breakeven_reached = True # Prevent normal break-even logic from overwriting this

        # Live PNL Logging
        now = datetime.now()
        if (now - self.last_pnl_heartbeat_time).total_seconds() >= 30: # Log every 30 seconds
            logger.info(f"[LIVE PNL] {self.option_symbol} | LTP: {current_opt_price:.2f} | PNL: ₹{current_floating_pnl:.2f} | SL: {self.current_sl:.2f}")
            self.last_pnl_heartbeat_time = now

        # 1. Check SL / TTP Hit
        if current_opt_price <= self.current_sl:
            reason = "Trailing Take Profit Hit" if self.target_reached else ("Break Even Hit" if self.breakeven_reached else "Stop Loss Hit")
            self.exit_trade(reason)
            return

        profit_pct = (current_opt_price - self.entry_price) / self.entry_price

        # 2. Update Trailing Take Profit (Target Reached)
        if profit_pct >= self.trade_target_pct:
            if not self.target_reached:
                logger.info(f"Target Reached! Activating Trailing Take Profit.")
                self.target_reached = True

            new_sl = self.risk_manager.update_trailing_take_profit(current_opt_price, self.current_sl, self.max_opt_price_seen, self.trade_trailing_pct)
            if new_sl > self.current_sl:
                logger.info(f"Trailing Take Profit updated to {new_sl}")
                self.current_sl = new_sl
                # In reality, modify the pending SL-M order with the broker here

        # 3. Update to Break Even (1:1 RR Reached)
        elif profit_pct >= self.trade_sl_pct and not self.target_reached and not self.breakeven_reached:
            self.breakeven_reached = True
            new_sl = self.entry_price * 1.01 # Slightly above entry to cover fees
            logger.info(f"1:1 R:R Reached. Moving SL to Break Even: {new_sl:.2f}")
            self.current_sl = new_sl
            # In reality, modify the pending SL-M order with the broker here

        # 4. Continuous Step Trailing (Between Break-Even and Target)
        elif self.breakeven_reached and not self.target_reached:
            # Trail behind by a wider margin (e.g. initial SL pct) to give it room to hit target
            # This locks in gains if the price reverses midway before hitting the final target
            new_sl = self.risk_manager.update_trailing_take_profit(current_opt_price, self.current_sl, self.max_opt_price_seen, self.trade_sl_pct)
            if new_sl > self.current_sl:
                logger.info(f"Step-Trailing SL up to lock in profit: {new_sl:.2f}")
                self.current_sl = new_sl

    def run_cycle(self):
        """Main strategy loop executed every tick/candle."""
        # Sync mock PNL to risk manager for paper trading kill switch
        if PAPER_TRADING:
            self.risk_manager.daily_pnl = self.daily_realized_pnl

        if self.risk_manager.check_kill_switch():
            if self.in_position:
                self.exit_trade("Kill Switch Triggered")
            return

        if self.in_position:
            self.manage_open_position()
            return

        # Fetch market data and indicators
        market_data = self.fetch_and_calculate_indicators()
        if not market_data:
            return

        timestamp = market_data['timestamp']
        close_price = market_data['close']
        open_price = market_data['open']
        high_price = market_data['high']
        low_price = market_data['low']
        r_high = market_data['rolling_high']
        r_low = market_data['rolling_low']
        ema = market_data['ema']
        vwap = market_data['vwap']
        adx = market_data['adx']
        adx_slope = market_data['adx_slope']
        rsi = market_data['rsi']

        # ==========================================
        # FILTERS & ENTRY LOGIC
        # ==========================================
        current_reason = "Waiting for setup."

        # ==========================================
        # STRATEGY 1: SIDEWAYS / CHOPPY MARKET
        # ==========================================
        if adx < ADX_THRESHOLD:
            # Supply & Demand Scalping (Mean-Reversion off extremes)
            if low_price <= r_low and close_price > r_low and rsi < 45:
                logger.info("Demand Zone Rejection Detected (Sideways Market).")
                self.execute_trade("CE", close_price, adx)
                return
            elif high_price >= r_high and close_price < r_high and rsi > 55:
                logger.info("Supply Zone Rejection Detected (Sideways Market).")
                self.execute_trade("PE", close_price, adx)
                return

            current_reason = f"Sideways Market (ADX {adx:.2f} < {ADX_THRESHOLD}). Waiting for Supply/Demand touch."

        else:
            # ==========================================
            # STRATEGY 2: MOMENTUM / TRENDING MARKET
            # ==========================================
            # Chop Killer: Ensure price is expanding away from VWAP
            vwap_distance_pct = abs(close_price - vwap) / vwap

            # Determine if we are in the market open period (first 45 mins)
            market_open_time = timestamp.replace(hour=9, minute=15, second=0, microsecond=0)
            time_since_open = timestamp - market_open_time
            is_market_open_period = time_since_open.total_seconds() <= 45 * 60

            if vwap_distance_pct <= 0.0005 and not is_market_open_period:
                current_reason = f"Price too close to VWAP (Chop Zone)"

            else:
                # 1. Breakout Strategy
                # Long CE: Price breaks Rolling High AND Price is expanding above VWAP/EMA AND RSI > 50
                if close_price > r_high and close_price > vwap and close_price > ema and rsi > 50:
                    logger.info("Bullish Breakout Detected.")
                    self.execute_trade("CE", close_price, adx)
                    return

                # Long PE: Price breaks Rolling Low AND Price is expanding below VWAP/EMA AND RSI < 50
                elif close_price < r_low and close_price < vwap and close_price < ema and rsi < 50:
                    logger.info("Bearish Breakdown Detected.")
                    self.execute_trade("PE", close_price, adx)
                    return

                # 2. Mean-Reversion Strategy
                # Bullish Rejection: Wick poked below rolling low, closed above, in an uptrend, RSI > 50
                elif low_price < r_low and close_price > r_low and close_price > open_price and close_price > vwap and close_price > ema and rsi > 50:
                    logger.info("Bullish Mean-Rejection Detected.")
                    self.execute_trade("CE", close_price, adx)
                    return

                # Bearish Rejection: Wick poked above rolling high, closed below, in a downtrend, RSI < 50
                elif high_price > r_high and close_price < r_high and close_price < open_price and close_price < vwap and close_price < ema and rsi < 50:
                    logger.info("Bearish Mean-Rejection Detected.")
                    self.execute_trade("PE", close_price, adx)
                    return

                else:
                    if close_price <= r_high and close_price >= r_low:
                        current_reason = "Price is trapped inside 30-min Rolling Range"
                    elif rsi <= 50 and close_price > vwap:
                        current_reason = "Price is bullish, but RSI < 50 does not confirm momentum"
                    elif rsi >= 50 and close_price < vwap:
                        current_reason = "Price is bearish, but RSI > 50 does not confirm momentum"
                    else:
                        current_reason = "Awaiting convergence of VWAP, EMA, and Breakout levels"

        # --- Heartbeat Logging ---
        # Print a status update every 5 minutes so the user knows what the bot is thinking
        now = datetime.now()
        if (now - self.last_heartbeat_time).total_seconds() >= 300: # 300 seconds = 5 mins
            logger.info(f"[HEARTBEAT] NIFTY LTP: {close_price:.2f} | ADX: {adx:.2f} | RSI: {rsi:.2f}")
            logger.info(f"[STATUS] Skipping Trade: {current_reason}")
            self.last_heartbeat_time = now
        # -------------------------

# ==========================================
# MAIN EXECUTION
# ==========================================
if __name__ == "__main__":
    broker = BrokerAPI()
    bot = ScalpingStrategy(broker)

    logger.info("Starting Options Scalping Bot...")

    try:
        while True:
            now = datetime.now().time()

            # Intraday MIS strict timings (09:15 AM to 03:15 PM)
            # We halt entries and square off everything by 15:15 to prevent overnight theta decay gaps
            start_time = datetime.strptime("09:15", "%H:%M").time()
            mis_square_off_time = datetime.strptime("15:15", "%H:%M").time()

            if start_time <= now < mis_square_off_time:
                bot.run_cycle()

            elif now >= mis_square_off_time:
                if bot.in_position:
                    logger.warning("MIS Square Off Time Reached (15:15). Closing all open intraday positions!")
                    bot.exit_trade("MIS Auto Square Off (15:15)")

                # If market is fully closed, exit loop
                if now > datetime.strptime("15:30", "%H:%M").time():
                    logger.info("Market Closed for the day. Exiting.")
                    logger.info(f"===================================")
                    logger.info(f"FINAL DAILY PNL: ₹{bot.daily_realized_pnl:.2f}")
                    logger.info(f"===================================")
                    break

            # Wait for next cycle
            time.sleep(1)

    except KeyboardInterrupt:
        logger.info("Bot stopped manually.")
        if bot.in_position:
            bot.exit_trade("Manual Stop")
        logger.info(f"===================================")
        logger.info(f"FINAL DAILY PNL: ₹{bot.daily_realized_pnl:.2f}")
        logger.info(f"===================================")
